apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  annotations:
    github.com/project-slug: wings-software/payment-service
spec:
  type: other
  lifecycle: unknown
  owner: Field_Engineering
