pipeline:
    name: payment-service
    identifier: paymentserviceweb
    projectIdentifier: DevX_Demo
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: nikpwingssoftware
                repoName: payment-service
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: nikpgkecluster
                          namespace: payment-service-build
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: RestoreCache
                                identifier: RestoreCache
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    bucket: nikp-maven
                                    key: payment-service-ci
                                    archiveFormat: Tar
                                    resources:
                                        limits:
                                            memory: 512Mi
                                            cpu: "0.5"
                          - parallel:
                                - step:
                                      type: RunTests
                                      name: runTestsWithIntelligence
                                      identifier: runTestsWithIntelligence
                                      spec:
                                          connectorRef: nikpdockerhub
                                          image: maven:<+pipeline.variables.mavenversion>-jdk-<+pipeline.variables.javaversion>
                                          language: Java
                                          buildTool: Maven
                                          args: test
                                          packages: com.nikp.
                                          runOnlySelectedTests: true
                                          preCommand: cd payment-service
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                          envVariables:
                                              DRONE_COMMIT_SHA: any
                                              DRONE_REMOTE_URL: any
                                              DRONE_SOURCE_BRANCH: any
                                              DRONE_TARGET_BRANCH: any
                                              MAVEN_OPTS: -Dmaven.repo.local=/harness/maven/repository
                                              CONTAINER_STEP: "3"
                                          resources:
                                              limits:
                                                  memory: 1Gi
                                                  cpu: "2"
                                - step:
                                      type: Plugin
                                      name: cleanup
                                      identifier: cleanup
                                      spec:
                                          connectorRef: nikpdockerhub
                                          image: nikpap/githubcli:v2
                                          privileged: false
                                          settings:
                                              GITHUB_TOKEN: <+secrets.getValue("githubtoken")>
                                              GITHUB_USERNAME: nikpapag
                                              GITHUB_EMAIL: nikpap.cs@icloud.com
                                          imagePullPolicy: Always
                                      failureStrategies:
                                          - onFailure:
                                                errors:
                                                    - Unknown
                                                action:
                                                    type: Ignore
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: nikpdockerhub
                                    image: maven:<+pipeline.variables.mavenversion>-jdk-<+pipeline.variables.javaversion>
                                    command: |-
                                        cd payment-service
                                        mvn -Dmaven.test.skip=true clean install -X
                                    privileged: false
                                    envVariables:
                                        MAVEN_OPTS: -Dmaven.repo.local=/harness/maven/repository
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheS3
                                name: Savemavenrepo
                                identifier: Savemavenrepo
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    bucket: nikp-maven
                                    key: payment-service-ci
                                    sourcePaths:
                                        - ./maven/repository
                                    archiveFormat: Tar
                                    override: true
                                    resources:
                                        limits:
                                            memory: 512Mi
                                            cpu: "0.5"
                          - step:
                                type: BuildAndPushECR
                                name: pushToECR
                                identifier: pushToECR
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    account: "759984737373"
                                    imageName: payment-service
                                    tags:
                                        - <+pipeline.sequenceId>
                                    dockerfile: /harness/payment-service/Dockerfile
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                when:
                                    stageStatus: Success
                                    condition: <+pipeline.variables.seusername> == 'aws'
                                failureStrategies: []
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: pushToDockerHub
                                identifier: pushToDockerHub
                                spec:
                                    connectorRef: nikpdockerhub
                                    repo: nikpap/payment-service
                                    tags:
                                        - <+pipeline.sequenceId>
                                    dockerfile: /harness/payment-service/Dockerfile
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                  serviceConfig:
                      serviceRef: ""
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
              when:
                  pipelineStatus: Success
              variables: []
    
    variables:
        - name: mavenversion
          type: String
          default: "3.8"
          value: <+input>
        - name: javaversion
          type: String
          default: "8"
          value: <+input>
        - name: servicename
          type: String
          default: payment-service
          value: <+input>
        - name: seusername
          type: String
          value: <+input>
        - name: ffsdkkeyprod
          type: String
          default: 44c9dcaa-dab2-4100-b2b5-75bdeb7aa497
          value: <+input>
