pipeline:
    name: payment-service-error-tracking
    identifier: paymentservicewebcvtest
    projectIdentifier: DevX_Demo
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: nikpwingssoftware
                repoName: payment-service
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: nikpgkecluster
                          namespace: payment-service-build
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: RestoreCache
                                identifier: RestoreCache
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    bucket: nikp-maven
                                    key: payment-service-ci
                                    archiveFormat: Tar
                                    resources:
                                        limits:
                                            memory: 512Mi
                                            cpu: "0.5"
                          - parallel:
                                - step:
                                      type: RunTests
                                      name: runTestsWithIntelligence
                                      identifier: runTestsWithIntelligence
                                      spec:
                                          connectorRef: nikpdockerhub
                                          image: maven:<+pipeline.variables.mavenversion>-jdk-<+pipeline.variables.javaversion>
                                          language: Java
                                          buildTool: Maven
                                          args: test
                                          packages: com.nikp.
                                          runOnlySelectedTests: true
                                          preCommand: cd payment-service
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                          envVariables:
                                              DRONE_COMMIT_SHA: any
                                              DRONE_REMOTE_URL: any
                                              DRONE_SOURCE_BRANCH: any
                                              DRONE_TARGET_BRANCH: any
                                              MAVEN_OPTS: -Dmaven.repo.local=/harness/maven/repository
                                              CONTAINER_STEP: "3"
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "2"
                                - step:
                                      type: Plugin
                                      name: cleanup
                                      identifier: cleanup
                                      spec:
                                          connectorRef: nikpdockerhub
                                          image: nikpap/githubcli:v2
                                          privileged: false
                                          settings:
                                              GITHUB_TOKEN: <+secrets.getValue("githubtoken")>
                                              GITHUB_USERNAME: nikpapag
                                              GITHUB_EMAIL: nikpap.cs@icloud.com
                                          imagePullPolicy: Always
                                      failureStrategies:
                                          - onFailure:
                                                errors:
                                                    - Unknown
                                                action:
                                                    type: Ignore
                                      when:
                                          stageStatus: Success
                                          condition: <+pipeline.variables.deletepr> == 'yes'
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: nikpdockerhub
                                    image: maven:<+pipeline.variables.mavenversion>-jdk-<+pipeline.variables.javaversion>
                                    command: |-
                                        cd payment-service
                                        mvn -Dmaven.test.skip=true clean install -X
                                    privileged: false
                                    envVariables:
                                        MAVEN_OPTS: -Dmaven.repo.local=/harness/maven/repository
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheS3
                                name: Savemavenrepo
                                identifier: Savemavenrepo
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    bucket: nikp-maven
                                    key: payment-service-ci
                                    sourcePaths:
                                        - ./maven/repository
                                    archiveFormat: Tar
                                    override: true
                                    resources:
                                        limits:
                                            memory: 512Mi
                                            cpu: "0.5"
                          - step:
                                type: BuildAndPushECR
                                name: pushToECR
                                identifier: pushToECR
                                spec:
                                    connectorRef: nikpaws
                                    region: eu-west-2
                                    account: "759984737373"
                                    imageName: payment-service
                                    tags:
                                        - <+pipeline.sequenceId>
                                    dockerfile: /harness/payment-service/Dockerfile
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                when:
                                    stageStatus: Success
                                    condition: <+pipeline.variables.seusername> == 'aws'
                                failureStrategies: []
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: pushToDockerHub
                                identifier: pushToDockerHub
                                spec:
                                    connectorRef: nikpdockerhub
                                    repo: nikpap/payment-service
                                    tags:
                                        - <+pipeline.sequenceId>
                                    dockerfile: /harness/payment-service/Dockerfile
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "2"
                  serviceConfig:
                      serviceRef: ""
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
              when:
                  pipelineStatus: Success
              variables: []
        - stage:
              name: DeployDev
              identifier: DeployDev
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests:
                                  - manifest:
                                        identifier: templates
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: nikpgithub
                                                    gitFetchType: Branch
                                                    paths:
                                                        - templates
                                                    repoName: payment-service-nonprod
                                                    branch: master
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: nikpgithub
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values-non-prod.yaml
                                                    repoName: payment-service-nonprod
                                                    branch: master
                              artifacts:
                                  sidecars: []
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: nikpdockerhub
                                          imagePath: nikpap/payment-service
                                          tag: <+pipeline.sequenceId>
                              variables: []
                      serviceRef: paymentservice
                  infrastructure:
                      environmentRef: GKEDEV
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: nikpgkecluster
                              namespace: payment-service-dev
                              releaseName: release-1
                      allowSimultaneousDeployments: true
                      infrastructureKey: ""
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              when:
                  pipelineStatus: Success                  
    variables:
        - name: mavenversion
          type: String
          default: "3.8"
          value: <+input>
        - name: javaversion
          type: String
          default: "8"
          value: <+input>
        - name: servicename
          type: String
          default: payment-service
          value: <+input>
        - name: seusername
          type: String
          default: et
          value: <+input>
        - name: ffsdkkeyprod
          type: String
          default: 44c9dcaa-dab2-4100-b2b5-75bdeb7aa497
          value: <+input>
        - name: isingress
          type: Number
          default: 1
          value: <+input>.allowedValues(0,1)
        - name: dbuser
          type: String
          value: <+secrets.getValue("dbuser")>
        - name: dbpassword
          type: String
          value: <+secrets.getValue("dbpassword")>
        - name: COLLECTOR_URL
          type: String
          value: https://app.harness.io/gratis/et-collector
