pipeline:
  name: payment-service-srm-data-generator
  identifier: paymentservicedata
  projectIdentifier: DevX_Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DeployProd
        identifier: DeployProd
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: paymentservicesrm_dev
            serviceDefinition:
              type: Kubernetes
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: templates
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: nikpgithub
                            gitFetchType: Branch
                            paths:
                              - templates-prod
                            repoName: payment-service-nonprod
                            branch: master
                        skipResourceVersioning: false
                  - manifest:
                      identifier: values
                      type: Values
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: nikpgithub
                            gitFetchType: Branch
                            paths:
                              - values-non-prod.yaml
                            repoName: payment-service-nonprod
                            branch: master
                artifacts:
                  primary:
                    spec:
                      connectorRef: nikpdockerhub
                      imagePath: nikpap/payment-service
                      tagRegex: "410"
                    type: DockerRegistry
          infrastructure:
            environmentRef: GKEPROD
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: nikpgkecluster
                namespace: payment-service
                releaseName: release-1
            allowSimultaneousDeployments: true
            infrastructureKey: ""
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDepoyment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        type: Verify
                        name: verify_canary
                        identifier: verify_dev
                        spec:
                          type: Canary
                          spec:
                            sensitivity: LOW
                            duration: 5m
                            deploymentTag: <+serviceConfig.artifacts.primary.tag>
                          monitoredService:
                            type: Default
                            spec: {}
                        timeout: 2h
                        failureStrategies:
                          - onFailure:
                              errors:
                                - Verification
                              action:
                                type: Ignore
                          - onFailure:
                              errors:
                                - Unknown
                              action:
                                type: ManualIntervention
                                spec:
                                  timeout: 2h
                                  onTimeout:
                                    action:
                                      type: Ignore
                        when:
                          stageStatus: Success
                          condition: <+pipeline.variables.verify_fail> == "false"
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
                  rollbackSteps:
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDepoyment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
                  rollbackSteps:
                    - step:
                        name: Rolling Rollback
                        identifier: rollingRollback
                        type: K8sRollingRollback
                        timeout: 10m
                        spec: {}
              - step:
                  type: ShellScript
                  name: WrapUp
                  identifier: WrapUp
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Wrapping up deployment"
                          url="http://$subdomain.cie-demo.co.uk"
                          export application="$url"
                          echo "$seusername"
                    environmentVariables:
                      - name: subdomain
                        type: String
                        value: <+pipeline.variables.seusername>
                      - name: seusername
                        type: String
                        value: <+pipeline.variables.seusername>
                    outputVariables:
                      - name: application
                        type: String
                        value: application
                    executionTarget: {}
                  timeout: 10m
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
  variables:
    - name: mavenversion
      type: String
      default: "3.8"
      value: <+input>
    - name: javaversion
      type: String
      default: "8"
      value: <+input>
    - name: servicename
      type: String
      default: paymentservice
      value: <+input>.allowedValues(paymentservice,paymentservicesrm_dev)
    - name: seusername
      type: String
      default: srmdecrease
      value: <+input>
    - name: ffsdkkeyprod
      type: String
      default: 44c9dcaa-dab2-4100-b2b5-75bdeb7aa497
      value: <+input>
    - name: isingress
      type: String
      default: "1"
      value: <+input>.allowedValues(1,0)
    - name: verify_fail
      type: String
      default: "false"
      value: <+input>.allowedValues(true,false)
    - name: dbuser
      type: String
      value: <+secrets.getValue("dbuser")>
    - name: dbpassword
      type: String
      value: <+secrets.getValue("dbpassword")>
  flowControl:
    barriers:
      - name: Barrier
        identifier: Barrier
